//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Dynamic_Event_Data
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class DITS_EventEntities : DbContext
    {
        public DITS_EventEntities()
            : base("name=DITS_EventEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<M_Activity> M_Activity { get; set; }
        public virtual DbSet<M_Barcode> M_Barcode { get; set; }
        public virtual DbSet<M_Company> M_Company { get; set; }
        public virtual DbSet<M_Employee> M_Employee { get; set; }
        public virtual DbSet<M_UserLogon> M_UserLogon { get; set; }
        public virtual DbSet<sysdiagram> sysdiagrams { get; set; }
        public virtual DbSet<T_Activity> T_Activity { get; set; }
        public virtual DbSet<T_News> T_News { get; set; }
        public virtual DbSet<T_Zone> T_Zone { get; set; }
    }
}
