//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Dynamic_Event_Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class M_Activity
    {
        public M_Activity()
        {
            this.T_Activity = new HashSet<T_Activity>();
        }
    
        public string ActivityNo { get; set; }
        public string ActivityName { get; set; }
        public Nullable<bool> IsActive { get; set; }
    
        public virtual ICollection<T_Activity> T_Activity { get; set; }
    }
}
