//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Dynamic_Event_Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class M_Employee
    {
        public M_Employee()
        {
            this.M_Barcode = new HashSet<M_Barcode>();
        }
    
        public int EmpId { get; set; }
        public string EmpCardNo { get; set; }
        public string CompanyNo { get; set; }
        public string EmpName { get; set; }
        public string CreatedUser { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public string UpdateUser { get; set; }
        public Nullable<System.DateTime> UpdatedDate { get; set; }
        public Nullable<bool> IsActive { get; set; }
    
        public virtual ICollection<M_Barcode> M_Barcode { get; set; }
        public virtual M_Company M_Company { get; set; }
    }
}
