//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Dynamic_Event_Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class T_Zone
    {
        public string ZoneNo { get; set; }
        public string ZoneName { get; set; }
        public string CompanyNo { get; set; }
    }
}
